# -*- coding: utf-8 -*-
"""Rule based bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jK0UDkwtLC36ilDqcpvfvMvfGNYY61dN
"""

import re
import random

class RuleBot:
  #potential negative response
  negative_responses=("no","nope","naw","nah","not a chance","sorry")
  #exit converstion keywords
  exit_comands=("quit","pause","exit","goodbye","bye","later")